// 灵镜 合规 — AI 生成标识(ffmpeg 后处理)。
//
// 决策来源:实测确认 wan2.2-s2v 成品不自带 AI 标识(/plan-eng-review §I1)。
// 融媒体/政企硬门票:给视频右下角打"AI 合成"半透明文字 + 写元数据。
// 受 tenant_setting 的 ai_label_enabled 开关控制(关了就跳过)。

import { spawn } from 'node:child_process';
import { writeFile, readFile, unlink, mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

/** ffmpeg 是否可用(容器/CI 里可能没装;没装则跳过标识并告警)。 */
let ffmpegChecked: boolean | null = null;
function ffmpegAvailable(): Promise<boolean> {
  if (ffmpegChecked !== null) return Promise.resolve(ffmpegChecked);
  return new Promise((resolve) => {
    const p = spawn('ffmpeg', ['-version']);
    p.on('error', () => { ffmpegChecked = false; resolve(false); });
    p.on('close', (code) => { ffmpegChecked = code === 0; resolve(ffmpegChecked); });
  });
}

function runFfmpeg(args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const p = spawn('ffmpeg', args);
    let stderr = '';
    p.stderr.on('data', (d) => (stderr += d.toString()));
    p.on('error', reject);
    p.on('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`ffmpeg 退出码 ${code}: ${stderr.slice(-500)}`));
    });
  });
}

/**
 * 用 ffprobe 读音频时长(秒)。ffprobe 不可用时返回 null(调用方据此跳过校验)。
 * wan2.2-s2v 要求驱动音频 <20s,故 TTS 后需校验。
 */
export async function probeAudioDuration(audioBuf: Buffer): Promise<number | null> {
  if (!(await ffmpegAvailable())) return null; // ffmpeg 套件缺失则跳过
  const dir = await mkdtemp(join(tmpdir(), 'lj-probe-'));
  const inPath = join(dir, 'a.mp3');
  try {
    await writeFile(inPath, audioBuf);
    return await new Promise<number | null>((resolve) => {
      const p = spawn('ffprobe', [
        '-v', 'error', '-show_entries', 'format=duration',
        '-of', 'default=noprint_wrappers=1:nokey=1', inPath,
      ]);
      let out = '';
      p.stdout.on('data', (d) => (out += d.toString()));
      p.on('error', () => resolve(null));
      p.on('close', () => {
        const n = parseFloat(out.trim());
        resolve(Number.isFinite(n) ? n : null);
      });
    });
  } finally {
    await unlink(inPath).catch(() => {});
  }
}

export interface LabelOptions {
  text?: string; // 标识文案,默认"AI 合成"
}

/**
 * 给视频加 AI 生成标识。返回处理后的视频 Buffer。
 * ffmpeg 不可用时:返回原视频 + 标记 applied=false(不阻断生成,但告警)。
 */
export async function applyAiLabel(
  videoBuf: Buffer,
  opts: LabelOptions = {},
): Promise<{ buffer: Buffer; applied: boolean }> {
  if (!(await ffmpegAvailable())) {
    return { buffer: videoBuf, applied: false };
  }
  const text = opts.text || 'AI 合成';
  const dir = await mkdtemp(join(tmpdir(), 'lj-label-'));
  const inPath = join(dir, 'in.mp4');
  const outPath = join(dir, 'out.mp4');
  try {
    await writeFile(inPath, videoBuf);
    // drawtext:右下角半透明白字 + 黑描边;metadata:写 comment 标记 AI 生成
    const filter =
      `drawtext=text='${text}':fontcolor=white@0.85:fontsize=h/22:` +
      `box=1:boxcolor=black@0.35:boxborderw=8:x=w-tw-24:y=h-th-24`;
    await runFfmpeg([
      '-y',
      '-i', inPath,
      '-vf', filter,
      '-metadata', `comment=AI-generated by Lingjing (${text})`,
      '-metadata', 'ai_generated=true',
      '-codec:a', 'copy',
      outPath,
    ]);
    const out = await readFile(outPath);
    return { buffer: out, applied: true };
  } finally {
    await unlink(inPath).catch(() => {});
    await unlink(outPath).catch(() => {});
  }
}
